package servent.message;

public enum MessageType {
	POISON, TOKEN, NEW_NODE, WELCOME, SORRY, UPDATE,
	JOINED, QUIT, QUIT_PREDECESSOR, QUIT_OK, QUIT_UPDATE,
	ADD, ADD_SUCCESS, ASK_PULL, TELL_PULL, REMOVE,
	COMMIT,	COMMIT_CONFLICT, COMMIT_SUCCESS, COMMIT_RESOLVE, COMMIT_ERROR
}
